### PR TITLE
Trying to update my fork

### PR DESCRIPTION
**Pull request by AnTi-ArT**
I hope this works -_-

### CODE REVIEW

**Comment by achadwick** [comment]
You don;t need to use a PR to update your own stuff.

I suggest you rebase against master to put your own changes on top. Or extract them as a diff file somehow and apply them separately.

**Comment by AnTi-ArT** [comment]
(I hate git!) I _tried_ to follow [this guide](http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381). But got stuck at unresolved conflicts (I hate git). So instead I thought it would be easier to just make a clean new libmypaint fork and copy my ten lines of code over manually, pull request and be done with it (I hate git). But it seems like the windows build process with scons and the libmypaint submodule is broken/discontinued since yesterday (which is not that big a problem, because i can build the version from a few days ago). Anyway, tomorrow I will first need to read about rebases, remotes, forks and branches (I hate git)...

**Comment by achadwick** [comment]
/nods oh, git. :anguished: 

Yeah, sorry about the Windows build docs. Fix hopefully soon. but I'm really busy with family stuff at the moment, to make matters more difficult. I need to get a mypaint-git PKGBUILD into MSYS2's repo alongside [the libmypaint-git one I made a few days earlier](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libmypaint-git), then update our windows testers' docs to just build from those. Less to type, and it's cleaner having the lib as something you can just remove or upgrade! It might generate good building blocks for fixing the AppVeyor test-build too, or extending it to MyPaint.

Let me know if you want a hand resolving the conflicts.

**Comment by AnTi-ArT** [comment]
No worries :) I managed to set up local branches of mypaint + libmypaint from a few days back that work fine. So I can actually try some stuff. I already got that old offset code in it. So when the official version is fixed I can fork and hopefull PR it. nice and clean...

**Pull request closed without merging**
